---

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - always

- include: "repo-{{ ansible_os_family }}.yml"
  when: dnsdist_install_repo != ""
  tags:
    - install
    - repository

- include: install.yml
  tags:
    - install

- name: Create encryption key
  block:
#    shell: "{{ ansible_python_interpreter }} -c 'import base64; import secrets; print(\"{}\".format(base64.b64encode(secrets.token_bytes(32)).decode(\"utf-8\")))'"
    - name: Generate encryption key
      shell: head -c 32 /dev/urandom | base64
      register: dnsdist_setkey_cmd
    - name: base64 encode encyption key
      set_fact:
        dnsdist_setkey: "{{ dnsdist_setkey_cmd.stdout }}"
  when: dnsdist_setkey == ""
  tags:
    - install
    - configure

- include: configure.yml
  tags:
    - configure

- name: Set the status of the dnsdist service
  service:
    name: dnsdist
    state: "{{ dnsdist_service_state }}"
    enabled: "{{ dnsdist_service_enabled }}"
  tags:
    - service
