---

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - always

- include: "repo-{{ ansible_os_family }}.yml"
  when: dnsdist_install_repo != ""
  tags:
    - install
    - repository

- include: install.yml
  tags:
    - install

- name: Create encryption key
  block:
    - name: Generate encryption key
      shell: head -c 32 /dev/urandom | base64
      register: dnsdist_setkey_cmd
    - name: base64 encode encyption key
      set_fact:
        dnsdist_setkey: "{{ dnsdist_setkey_cmd.stdout }}"
    - name: Register key to file
      copy:
        content: "{{ dnsdist_setkey_cmd.stdout }}"
        dest: "./{{ ansible_inventory_hostname }}.key"
      delegate_to: localhost
  when: dnsdist_setkey == ""
  tags:
    - install
    - configure

- include: configure.yml
  tags:
    - configure

- name: Set the status of the dnsdist service
  service:
    name: dnsdist
    state: "{{ dnsdist_service_state }}"
    enabled: "{{ dnsdist_service_enabled }}"
  tags:
    - service
